const Frame = require(script.Frame)
const ImageButton = require(script.ImageButton)
const ImageLabel = require(script.ImageLabel)
const ScrollingFrame = require(script.ScrollingFrame)
const TextButton = require(script.TextButton)
const TextLabel = require(script.TextLabel)
const UICorner = require(script.UICorner)
const UIGradient = require(script.UIGradient)
const UIGridLayout = require(script.UIGridLayout)
const UIListLayout = require(script.UIListLayout)
const UIPadding = require(script.UIPadding)
const UIStroke = require(script.UIStroke)

return {
	Frame = Frame,
	ImageButton = ImageButton,
	ImageLabel = ImageLabel,
	ScrollingFrame = ScrollingFrame,
	TextButton = TextButton,
	TextLabel = TextLabel,
	UICorner = UICorner,
	UIGradient = UIGradient,
	UIGridLayout = UIGridLayout,
	UIListLayout = UIListLayout,
	UIPadding = UIPadding,
	UIStroke = UIStroke,
}
